Repository vmware/global-load-balancing-services-for-kubernetes, pull requests merged in 2021-04, with the labels that each got.

#18 Bugfixes and integration testsuite for GDP and GSLB HostRule
  gslb/gslbutils/gdputils.go
  gslb/nodes/avi_model_nodes.go
  gslb/nodes/dq_ingestion.go
  gslb/test/avimockobjects/ap_mock.json
  gslb/test/avimockobjects/hm_mock.json
  gslb/test/integration/third_party_vips/gslb_hostrule_test.go
  gslb/test/integration/third_party_vips/ingress_test.go
  gslb/test/integration/third_party_vips/int_lib.go
  gslb/test/integration/third_party_vips/int_test.go
  gslb/test/mockaviserver/aviserver.go
Labels: cherry-pick-required, cla-not-required

#19 Return an error if health monitor is not federated
  gslb/ingestion/gdp_controller.go
  gslb/ingestion/gslb_host_rule.go
  gslb/test/avimockobjects/hm_mock.json
  gslb/test/integration/third_party_vips/gslb_hostrule_test.go
  gslb/test/integration/third_party_vips/int_lib.go
  gslb/test/mockaviserver/aviserver.go
Labels: cherry-pick-required, cla-not-required

#22 Add GDP invalid Health Monitor transition cases
  gslb/test/integration/third_party_vips/gslb_hostrule_test.go
  gslb/test/integration/third_party_vips/int_lib.go
Labels: cherry-pick-required, cla-not-required

#21 Skip initializing member cluster if HostRule CRD absent
  gslb/ingestion/gslb.go
  gslb/rest/dq_nodes.go
Labels: cherry-pick-required, cla-not-required

#23 Cherry-picks from origin/master
  gslb/ingestion/gslb.go
  gslb/rest/dq_nodes.go
Labels: cherry-pick, cla-not-required

#24 Fixes and integration tests for hostrules
  gslb/ingestion/gslb_host_rule.go
  gslb/ingestion/member_controllers.go
  gslb/nodes/dq_ingestion.go
  gslb/test/integration/custom_fqdn/custom_fqdn_test.go
  gslb/test/integration/custom_fqdn/hostrule_test.go
  gslb/test/integration/custom_fqdn/lib.go
  gslb/test/integration/third_party_vips/int_test.go
Labels: cherry-pick-required, cla-not-required

#14 Adding Unit Test for GSLBHostRule
  gslb/ingestion/gslb_host_rule.go
  gslb/test/avimockobjects/ap_mock.json
  gslb/test/avimockobjects/gslb_mock.json
  gslb/test/avimockobjects/hm_mock.json
  gslb/test/avimockobjects/validapplicationpersistenceprofile_mock.json
  gslb/test/avimockobjects/validhealthmonitor_mock.json
  gslb/test/ingestion/gslbhostrule_test.go
  gslb/test/ingestion/ingestion_test.go
  gslb/test/ingestion/lib.go
  gslb/test/mockaviserver/aviserver.go
Labels: cherry-pick-required, cla-not-required

#28 Add gslb pool algorithm as a configurable GS knob
  go.mod
  go.sum
  gslb/cache/controller_obj_cache.go
  gslb/gslbutils/gdputils.go
  gslb/gslbutils/gslbhr_utils.go
  gslb/gslbutils/gslbutils.go
  gslb/ingestion/gdp_controller.go
  gslb/ingestion/gslb_host_rule.go
  gslb/nodes/avi_model_nodes.go
  gslb/nodes/node_utils.go
  gslb/rest/dq_nodes.go
  gslb/test/integration/third_party_vips/gslb_hostrule_test.go
  gslb/test/integration/third_party_vips/ingress_test.go
  gslb/test/integration/third_party_vips/int_lib.go
  gslb/test/integration/third_party_vips/int_test.go
  helm/amko/crds/gdp_def.yaml
  helm/amko/crds/gslbhostrule_def.yaml
  internal/apis/amko/v1alpha1/types.go
  internal/apis/amko/v1alpha1/zz_generated.deepcopy.go
  internal/apis/amko/v1alpha2/types.go
  internal/apis/amko/v1alpha2/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: cherry-pick-required, cla-not-required

#29 Cherry-picks for algorithm support
  go.mod
  go.sum
  gslb/cache/controller_obj_cache.go
  gslb/gslbutils/gdputils.go
  gslb/gslbutils/gslbhr_utils.go
  gslb/gslbutils/gslbutils.go
  gslb/ingestion/gdp_controller.go
  gslb/ingestion/gslb_host_rule.go
  gslb/nodes/avi_model_nodes.go
  gslb/nodes/node_utils.go
  gslb/rest/dq_nodes.go
  gslb/test/integration/third_party_vips/gslb_hostrule_test.go
  gslb/test/integration/third_party_vips/ingress_test.go
  gslb/test/integration/third_party_vips/int_lib.go
  gslb/test/integration/third_party_vips/int_test.go
  helm/amko/crds/gdp_def.yaml
  helm/amko/crds/gslbhostrule_def.yaml
  internal/apis/amko/v1alpha1/types.go
  internal/apis/amko/v1alpha1/zz_generated.deepcopy.go
  internal/apis/amko/v1alpha2/types.go
  internal/apis/amko/v1alpha2/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: cherry-pick, cla-not-required

#30 Fixes for algorithm formatting and health monitor
  gslb/cache/controller_obj_cache.go
  gslb/nodes/avi_model_nodes.go
  gslb/rest/dq_nodes.go
Labels: cherry-pick-required, cla-not-required

#31 Cherry-picks for health monitor and algorithm fixes
  gslb/cache/controller_obj_cache.go
  gslb/nodes/avi_model_nodes.go
  gslb/rest/dq_nodes.go
Labels: cherry-pick, cla-not-required

#27 Add integration test commands to Makefile
  Makefile
Labels: cherry-pick-required, cla-not-required

#32 Figure out TLS ingress/route from HostRule
  gslb/gslbutils/gslbutils.go
  gslb/ingestion/event_handlers.go
  gslb/ingestion/member_controllers.go
  gslb/nodes/avi_model_nodes.go
  gslb/test/integration/custom_fqdn/hostrule_test.go
  gslb/test/integration/custom_fqdn/lib.go
Labels: cherry-pick-required, cla-not-required

#33 Don't remove health monitors if HM ref is provided
  gslb/ingestion/event_handlers.go
  gslb/rest/dq_nodes.go
  gslb/test/integration/third_party_vips/ingress_test.go
  gslb/test/integration/third_party_vips/int_lib.go
Labels: cherry-pick-required, cla-not-required

#34 Cherry-picks for Health monitor refs and other fixes
  Makefile
  gslb/gslbutils/gslbutils.go
  gslb/ingestion/event_handlers.go
  gslb/ingestion/member_controllers.go
  gslb/nodes/avi_model_nodes.go
  gslb/rest/dq_nodes.go
  gslb/test/integration/custom_fqdn/hostrule_test.go
  gslb/test/integration/custom_fqdn/lib.go
  gslb/test/integration/third_party_vips/ingress_test.go
  gslb/test/integration/third_party_vips/int_lib.go
Labels: cherry-pick, cla-not-required

#35 VS UUID fix and aviserver integration test cases
  gslb/gslbutils/gslbutils.go
  gslb/nodes/avi_model_nodes.go
  gslb/nodes/dq_ingestion.go
  gslb/rest/dq_nodes.go
  gslb/test/ingestion/ingresses_test.go
  gslb/test/integration/third_party_vips/ingress_test.go
  gslb/test/integration/third_party_vips/int_lib.go
  gslb/test/integration/third_party_vips/int_test.go
  gslb/test/mockaviserver/aviserver.go
Labels: cherry-pick-required, cla-not-required

#36 VS UUID fix and aviserver integration test cases
  gslb/gslbutils/gslbutils.go
  gslb/nodes/avi_model_nodes.go
  gslb/nodes/dq_ingestion.go
  gslb/rest/dq_nodes.go
  gslb/test/ingestion/ingresses_test.go
  gslb/test/integration/third_party_vips/ingress_test.go
  gslb/test/integration/third_party_vips/int_lib.go
  gslb/test/integration/third_party_vips/int_test.go
  gslb/test/mockaviserver/aviserver.go
Labels: cherry-pick, cla-not-required

#37 Fix custom HM delete issue while bootup
  gslb/gslbutils/gslbutils.go
  gslb/rest/dq_nodes.go
Labels: cherry-pick-required, cla-not-required

#38 Fix custom HM delete issue while bootup
  gslb/gslbutils/gslbutils.go
  gslb/rest/dq_nodes.go
Labels: cherry-pick, cla-not-required

#39 Fixes for custom HM change and algorithm parsing
  gslb/cache/controller_obj_cache.go
  gslb/nodes/avi_model_nodes.go
Labels: cherry-pick-required, cla-not-required

#40 Fixes for custom HM change and algorithm parsing
  gslb/cache/controller_obj_cache.go
  gslb/nodes/avi_model_nodes.go
Labels: cla-not-required

#41 React to local fqdn update in AKO HostRule
  gslb/ingestion/event_handlers.go
  gslb/ingestion/member_controllers.go
Labels: cherry-pick-required, cla-not-required

#42 React to local fqdn update in AKO HostRule
  gslb/ingestion/event_handlers.go
  gslb/ingestion/member_controllers.go
Labels: cherry-pick, cla-not-required

#43 Retry on all 401s except for Invalid Credentials
  gslb/cache/avi_ctrl.go
  gslb/cache/controller_obj_cache.go
  gslb/gslbutils/gslbutils.go
  gslb/ingestion/gslb_host_rule.go
  gslb/rest/dq_nodes.go
Labels: cherry-pick-required, cla-not-required

#44 Cherry picks for 401 error handling
  gslb/cache/avi_ctrl.go
  gslb/cache/controller_obj_cache.go
  gslb/gslbutils/gslbutils.go
  gslb/ingestion/gslb_host_rule.go
  gslb/rest/dq_nodes.go
Labels: cherry-pick, cla-not-required

#45 Fix for member cluster healthcheck
  gslb/ingestion/gslb.go
  gslb/nodes/dq_ingestion.go
  gslb/test/integration/custom_fqdn/custom_fqdn_test.go
  gslb/test/integration/third_party_vips/int_test.go
Labels: cherry-pick-required, cla-not-required

#46 Fix for member cluster healthcheck
  gslb/ingestion/gslb.go
  gslb/nodes/dq_ingestion.go
  gslb/test/integration/custom_fqdn/custom_fqdn_test.go
  gslb/test/integration/third_party_vips/int_test.go
Labels: cherry-pick, cla-not-required
