Repository vmware/global-load-balancing-services-for-kubernetes, pull requests merged in 2021-08, with the labels that each got.

#96 cherry picks from 1.4.2
  gslb/cache/controller_obj_cache.go
  gslb/gslbutils/gslbutils.go
  gslb/nodes/avi_model_nodes.go
  gslb/test/integration/custom_fqdn/custom_fqdn_test.go
  gslb/test/integration/third_party_vips/int_test.go
  internal/apis/amko/v1alpha1/types.go
Labels: cherry-pick, cla-not-required

#97 Don't update status if status already reflects that AMKO needs a reboot
  gslb/gslbutils/gslbutils.go
  gslb/ingestion/gslb.go
Labels: cla-not-required

#98 Set version as 1.5.1
  version.yaml
Labels: cla-not-required

#100 Update version to 1.6.1
  version.yaml
Labels: cla-not-required

#101 Shutdown API server if the GSLB leader IP is changed
  gslb/ingestion/gslb.go
Labels: cla-not-required, cherry-pick-required

#103 Shutdown API server if the GSLB leader IP is changed
  gslb/ingestion/gslb.go
Labels: cla-not-required, cherry-pick

#104 Sanitize the AMKO docs
  README.md
  docs/README.md
  docs/architecture.md
  docs/crds/amkocluster.md
  docs/crds/gslbconfig.md
  docs/crds/gslbhostrule.md
  docs/images/amko_arch.png
  docs/local_and_global_fqdn.md
  docs/site_recovery.md
  docs/troubleshooting.md
Labels: cla-not-required, cherry-pick-required

#105 Sanitize the AMKO docs
  README.md
  docs/README.md
  docs/architecture.md
  docs/crds/amkocluster.md
  docs/crds/gslbconfig.md
  docs/crds/gslbhostrule.md
  docs/images/amko_arch.png
  docs/local_and_global_fqdn.md
  docs/site_recovery.md
  docs/troubleshooting.md
Labels: cla-not-required, cherry-pick
