Repository vmware/global-load-balancing-services-for-kubernetes, pull requests merged in 2021-07, with the labels that each got.

#70 Federator should consolidate all GSLBConfigs and GDPs on member clusters
  federator/controllers/amkocluster_controller.go
  federator/controllers/status.go
  federator/controllers/suite_test.go
  federator/controllers/test_utils.go
  federator/controllers/utils.go
  gslb/ingestion/bootup_handler.go
Labels: cla-not-required

#72 Helm changes for federator
  Dockerfile.amko-federator
  Makefile
  federator/Dockerfile
  helm/amko/crds/amko.vmware.com_amkoclusters.yaml
  helm/amko/templates/amkocluster.yaml
  helm/amko/templates/clusterrole.yaml
  helm/amko/templates/statefulset.yaml
  helm/amko/values.yaml
Labels: cla-not-required

#71 tests for AMKO boot up checks and leader field change in AMKOCluster
  Makefile
  gslb/apiserver/apiserver.go
  gslb/ingestion/bootup_handler.go
  gslb/ingestion/gslb.go
  gslb/test/bootuptest/bootup_test.go
Labels: cla-not-required

#75 Update version to 1.4.2
  version.yaml
Labels: cla-not-required

#77 log error message before calling panic
  gslb/gslbutils/gslbutils.go
  gslb/ingestion/fullsync.go
  gslb/ingestion/gslb.go
Labels: cherry-pick, cla-not-required

#76 log error message before calling panic
  gslb/gslbutils/gslbutils.go
  gslb/ingestion/fullsync.go
  gslb/ingestion/gslb.go
Labels: cherry-pick-required, cla-not-required

#78 Fix error messages and logging
  federator/controllers/status.go
  federator/controllers/utils.go
  federator/main.go
  gslb/ingestion/bootup_handler.go
  gslb/nodes/avi_model_nodes.go
Labels: cherry-pick-required, cla-not-required

#79 Fix error messages and logging
  federator/controllers/status.go
  federator/controllers/utils.go
  federator/main.go
  gslb/ingestion/bootup_handler.go
  gslb/nodes/avi_model_nodes.go
Labels: cherry-pick, cla-not-required

#80 Enable logging to PVC if required for federator
  federator/controllers/log.go
  federator/main.go
  gslb/ingestion/gslb.go
Labels: cherry-pick-required, cla-not-required

#81 Enable logging to PVC if required for federator
  federator/controllers/log.go
  federator/main.go
  gslb/ingestion/gslb.go
Labels: cherry-pick, cla-not-required

#82 Fix parsing error for TTL value for a REST response
  gslb/cache/controller_obj_cache.go
Labels: cherry-pick-required, cla-not-required

#84 Fix validation of current AMKOCluster object while AMKO bootup
  federator/controllers/amkocluster_controller.go
  federator/controllers/utils.go
  gslb/ingestion/bootup_handler.go
  gslb/test/bootuptest/bootup_test.go
Labels: cherry-pick-required, cla-not-required

#83 Fix parsing error for TTL value for a REST response
  gslb/cache/controller_obj_cache.go
Labels: cherry-pick, cla-not-required

#85 Fix validation of current AMKOCluster object while AMKO bootup
  federator/controllers/amkocluster_controller.go
  federator/controllers/utils.go
  gslb/ingestion/bootup_handler.go
  gslb/test/bootuptest/bootup_test.go
Labels: cherry-pick, cla-not-required

#86 Add AMKO-Federator as the manager in Create operations as well
  federator/controllers/utils.go
Labels: cherry-pick-required, cla-not-required

#88 migrate AMKO docs and changelog from avi-helm-charts repository
  CHANGELOG.md
  docs/README.md
  docs/crds/gdp.md
  docs/crds/gslbconfig.md
  docs/crds/gslbhostrule.md
  docs/docs/local_and_global_fqdn.md
  docs/docs/site_recovery.md
  docs/docs/troubleshooting.md
  docs/images/amko_ako.jpg
  docs/images/amko_config.png
  docs/images/amko_ss.png
  docs/images/global_fqdn.png
  docs/images/local_fqdn.png
  docs/images/local_vs_global_fqdn.png
  docs/kubeconfig.md
Labels: cla-not-required

#87 Add AMKO-Federator as the manager in Create operations as well
  federator/controllers/utils.go
Labels: cherry-pick, cla-not-required

#89 Get Site Persistence from cache when GSs are fetched from Avi
  gslb/cache/controller_obj_cache.go
  gslb/ingestion/gslb_host_rule.go
Labels: cherry-pick-required, cla-not-required

#90 Get Site Persistence from cache when GSs are fetched from Avi
  gslb/cache/controller_obj_cache.go
  gslb/ingestion/gslb_host_rule.go
Labels: cherry-pick, cla-not-required

#92 Change useCustomGlobalFqdn to bool ptr
  gslb/gslbutils/gslbutils.go
  gslb/test/integration/custom_fqdn/custom_fqdn_test.go
  gslb/test/integration/third_party_vips/int_test.go
  internal/apis/amko/v1alpha1/types.go
Labels: cherry-pick-required, cla-not-required

#93 Update the health monitor path names only if no references
  gslb/cache/controller_obj_cache.go
  gslb/nodes/avi_model_nodes.go
Labels: cherry-pick-required, cla-not-required

#91 Add documentation for AMKO federator
  docs/README.md
  docs/federation.md
  docs/images/amko_fed_cluster_failure.png
  docs/images/amko_fed_initial.png
  docs/images/amko_fed_switch.png
Labels: cherry-pick-required, cla-not-required

#94 Documentation cherry-picks for 1.4.2
  CHANGELOG.md
  docs/README.md
  docs/crds/gdp.md
  docs/crds/gslbconfig.md
  docs/crds/gslbhostrule.md
  docs/docs/local_and_global_fqdn.md
  docs/docs/site_recovery.md
  docs/docs/troubleshooting.md
  docs/federation.md
  docs/images/amko_ako.jpg
  docs/images/amko_config.png
  docs/images/amko_fed_cluster_failure.png
  docs/images/amko_fed_initial.png
  docs/images/amko_fed_switch.png
  docs/images/amko_ss.png
  docs/images/global_fqdn.png
  docs/images/local_fqdn.png
  docs/images/local_vs_global_fqdn.png
  docs/kubeconfig.md
Labels: cherry-pick, cla-not-required

#95 Add changelogs for 1.4.2
  CHANGELOG.md
Labels: cla-not-required
