Repository vmware/global-load-balancing-services-for-kubernetes, pull requests merged in 2022-10, with the labels that each got.

#163 Changelogs for release 1.8.1
  CHANGELOG.md
  README.md
Labels: documentation, cla-not-required

#162 AV-149833 : SRP tool integration in AMKO build pipline
  hack/jenkins/save_build.sh
Labels: cla-not-required, cherry-pick-required

#165 AV-149833 : SRP tool integration in AMKO build pipline
  hack/jenkins/save_build.sh
Labels: cla-not-required

#167 AV-157643: Fixes deletion of health monitors specified in healthMonitorRefs from the controller
  gslb/rest/dq_nodes.go
Labels: cla-not-required

#166 cherry-pick of 1.8.1 release changelogs
  CHANGELOG.md
  README.md
Labels: cla-not-required, cherry-pick
