Repository vmware/global-load-balancing-services-for-kubernetes, pull requests merged in 2022-06, with the labels that each got.

#152 Changelog for 1.7.1
  CHANGELOG.md
  MAINTAINERS.md
  README.md
Labels: documentation, cherry-pick-required

#149 Documentation for Multiple FQDN support for AMKO
  docs/multiple_fqdn.md
Labels: documentation, cla-not-required, cherry-pick-required

#154 Document changes for Health monitor template
  docs/crds/gdp.md
  docs/crds/gslbhostrule.md
Labels: documentation, cla-not-required, cherry-pick-required

#155 Disable the service discovery
  helm/amko/templates/statefulset.yaml
  helm/amko/values.yaml
Labels: cla-not-required, cherry-pick-required
